---
- name: Restart Zookeeper
  systemd:
    daemon_reload: true
    name: "{{zookeeper_service_name}}"
    state: restarted
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ myuid }}"
  tags:
    - systemd

- name: Startup Delay
  wait_for:
    timeout: "{{ zookeeper_health_check_delay }}"
