---
### Installation of Confluent Platform on CentOS7.
### SASL Plain enabled.
### Control Plane listener enabled.
### Kafka Connect Confluent Hub Plugins logic (Installs jcustenborder/kafka-connect-spooldir:2.0.43).
### Custom Service Unit overrides.
### Custom log4j appender names.

driver:
  name: docker
platforms:
  - name: zookeeper1
    hostname: zookeeper1.confluent
    groups:
      - zookeeper
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka-broker1
    hostname: kafka-broker1.confluent
    groups:
      - kafka_broker
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka-broker2
    hostname: kafka-broker2.confluent
    groups:
      - kafka_broker
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka-broker3
    hostname: kafka-broker3.confluent
    groups:
      - kafka_broker
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: schema-registry1
    hostname: schema-registry1.confluent
    groups:
      - schema_registry
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka-rest1
    hostname: kafka-rest1.confluent
    groups:
      - kafka_rest
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: kafka-connect1
    hostname: kafka-connect1.confluent
    groups:
      - kafka_connect
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: ksql1
    hostname: ksql1.confluent
    groups:
      - ksql
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: control-center1
    hostname: control-center1.confluent
    groups:
      - control_center
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    published_ports:
      - "9021:9021"
    networks:
      - name: confluent
provisioner:
  inventory:
    host_vars:
      kafka-broker1:
        kafka_broker_custom_properties:
          broker.rack: dc1
          broker.id: 11
          num.partitions: 1
          replica.selector.class: org.apache.kafka.common.replica.RackAwareReplicaSelector
      kafka-broker2:
        kafka_broker_custom_properties:
          broker.rack: dc2
          broker.id: 12
          num.partitions: 2
          replica.selector.class: org.apache.kafka.common.replica.RackAwareReplicaSelector

    group_vars:
      all:
        sasl_protocol: plain
        kafka_broker_configure_control_plane_listener: true
        zookeeper_custom_properties:
          dataLogDir: /opt/zookeeper
        kafka_broker_custom_properties:
          confluent.security.event.logger.exporter.kafka.topic.replicas: 4
          auto.create.topics.enable: false
          authorizer.class.name: kafka.security.authorizer.AclAuthorizer
        kafka_connect_confluent_hub_plugins:
          - jcustenborder/kafka-connect-spooldir:2.0.43

        kafka_connect_connectors:
          - name: sample-connector-1
            config:
              connector.class: "org.apache.kafka.connect.tools.VerifiableSinkConnector"
              tasks.max: "1"
              file: "/etc/kafka/connect-distributed.properties"
              topics: "test_topic"

        zookeeper_service_unit_overrides:
          Description: Custom Zookeeper description

        zookeeper_log4j_root_logger: INFO, zkAppender

        kafka_broker_service_unit_overrides:
          Description: Custom Kafka description

        kafka_broker_log4j_root_logger: "INFO, kafkaAppender"

        schema_registry_log4j_root_logger: INFO, file

        kafka_connect_service_unit_overrides:
          Description: Custom Connect description

        kafka_connect_log4j_root_logger: "INFO, connectAppender"

        kafka_rest_service_unit_overrides:
          Description: Custom Rest Proxy description

        kafka_rest_log4j_root_logger: INFO, file

        ksql_service_unit_overrides:
          Description: Custom KSQLDB description

        ksql_log4j_root_logger: INFO, main

        control_center_service_unit_overrides:
          Description: Custom C3 description

        control_center_log4j_root_logger: INFO, stdout, main
      kafka_broker:
        kafka_broker_custom_properties:
          confluent.support.metrics.enable: false
          confluent.balancer.topic.replication.factor: 4
          confluent.license.topic.replication.factor: 4
          confluent.metadata.topic.replication.factor: 4


