---
name: Molecule CI
on: [push, pull_request]

jobs:
  test:
    name: Molecule
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: |
          pip3 install ansible==4.10.0 molecule "molecule-docker<=2.0.0" yamllint ansible-lint

      - name: Run Molecule tests.
        run: |
          git clone -b ANSIENG-1649 https://github.com/wadhwa1/cp-ansible.git ansible_collections/confluent/platform
          cd ansible_collections/confluent/platform
          molecule --debug converge -s plain-rhel
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

      - name: Setup SSH session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
