---
name: Molecule CI
on: [push, pull_request]

jobs:
  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - rockylinux8
          - debian10

    steps:
      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] yamllint ansible-lint

      - name: Run Molecule tests.
        run: |
          git clone https://github.com/confluentinc/cp-ansible.git ansible_collections/confluent/platform
          cd ansible_collections/confluent/platform
          molecule --debug converge -s plain-rhel
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3